### ISSUE TITLE
LDAP-80: Change the build system to maven

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#122]
["Mattias Hellborg Arthursson":https://jira.spring.io/secure/ViewProfile.jspa?name=marthursson](Migrated from ["LDAP-80":https://jira.spring.io/browse/LDAP-80?redirect=false]) said:

The directory structure must be changed to accommodate the maven module way of thinking. We should also prepare for running integration tests from a separate module, as well as migrating the jars into OSGi bundles. Something like this:

bc.. 
spring-ldap
  spring-ldap-core
    spring-ldap-core-bundle (spring-ldap.jar)
    spring-ldap-core-integration-test
  spring-ldap-odm
    spring-ldap-odm-bundle (spring-ldap-odm.jar)
    spring-ldap-odm-integration-test
  spring-ldap-tiger
    spring-ldap-tiger-bundle (spring-ldap-tiger.jar)
    spring-ldap-tiger-integration-test

p.

**Comment by spring-issuemaster** [comment]
This issue depends on #124
