### ISSUE TITLE
LDAP-81: Implement a Maven2 build system

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#123]
["Jasper Blues":https://jira.spring.io/secure/ViewProfile.jspa?name=jasper.blues](Migrated from ["LDAP-81":https://jira.spring.io/browse/LDAP-81?redirect=false]) said:
- The top spring-ldap directory should be the parent
- spring-ldap-odm should be a separate artifact
- spring-ldap-tiger should be a separate artifact.

**Comment by spring-issuemaster** [comment]
This issue duplicates #122
