### ISSUE TITLE
NullPointerException in DirContextAdapter

### ISSUE THREAD

**Issue by Khoulaiz** [spring-projects/spring-ldap#14]
There is a possible NullPointerException in org.springframework.ldap.core.DirContextAdapter.collectModifications(). If the modification introduces new Attributes, the `currentAttribute` will be null and a NPE will occure at line 338. Please also note the several checks for null of `currentAttribute` in the following if-clause.

**Comment by rwinch** [comment]
Thanks for the report this is fixed in https://jira.spring.io/browse/LDAP-304
