### ISSUE TITLE
LDAP-110: NoClassDefFoundError for PagedResultsControl

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#149]
["Nils-Åke Klittby":https://jira.spring.io/secure/ViewProfile.jspa?name=nilkli](Migrated from ["LDAP-110":https://jira.spring.io/browse/LDAP-110?redirect=false]) said:

When using the org.springframework.ldap.control.PagedResultsRequestControl class in java 5 or higher a NoClassDefFoundError for com.sun.jndi.ldap.ctl.PagedResultsControl is thrown.

**Comment by spring-issuemaster** [comment]
This issue duplicates #157
