### ISSUE TITLE
LDAP-129: Add support for java.util.Date

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#167]
["Mickael Istria":https://jira.spring.io/secure/ViewProfile.jspa?name=mickael_istria](Migrated from ["LDAP-129":https://jira.spring.io/browse/LDAP-129?redirect=false]) said:

Here is my LDAP date attribute:

bc.. 
AttributeType ( 1.2.250.1.16.6.11.349
  NAME 'i-creation-date'
  DESC 'Date de creation'
  EQUALITY generalizedTimeMatch
  SYNTAX 1.3.6.1.4.1.1466.115.121.1.24
  SINGLE-VALUE)

p. 

And a piece of my Java code responsible of binding it in an LDAP node:

bc.. 
    Attributes attr = new BasicAttributes();
    // ...
    Attribute att = new BasicAttribute(myAttribute, new Date());
    attr.put(att);
    // ...
    ldapTemplate.bind(dn, null, attributes);

p. 

This code causes"

bc.. 
org.springframework.ldap.InvalidAttributeValueException: Malformed 'i-creation-date' attribute value; nested exception is javax.naming.directory.InvalidAttributeValueException: Malformed 'i-creation-date' attribute value; remaining name 'cn=partner1220002373577, ou=partners, ou=people'

p. 

when "bind" is called.

I had to convert the Date to String using

bc.. 
    if (value instanceof Date) {
        Date date = (Date)value;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMddhhmmss");
        value = dateFormat.format(date).concat("Z");
    }

p. 

I think this should be added (if possible) in the part of Spring LDAP that is responsible of inserting an attribute in LDAP.

Regards,
Mickael

bc..

**Comment by kwin** [comment]
Wouldn't it be possible to instead provide an additional converter from String to Date leveraging the `Converter` interface. That would be used by ODM then automatically.
