### ISSUE TITLE
LDAP-130: DirContextAdapter getStringAttributes returns null

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#168]
["Brian Relph":https://jira.spring.io/secure/ViewProfile.jspa?name=relphie](Migrated from ["LDAP-130":https://jira.spring.io/browse/LDAP-130?redirect=false]) said:

from http://forum.springframework.org/showthread.php?t=59702

DirContextAdapter returns null when retrieving values for an attribute that does not exist.  Instead of null, perhaps return an empty array.  Or, Javadoc the potential null-value return.

**Comment by spring-issuemaster** [comment]
This issue depends on #175
