### ISSUE TITLE
LDAP-176: AD Range Retrieval support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#210]
["Marius Scurtescu":https://jira.spring.io/secure/ViewProfile.jspa?name=mariuss](Migrated from ["LDAP-176":https://jira.spring.io/browse/LDAP-176?redirect=false]) said:

Active Directory has a hard limit on the number of values it returns for an attribute. If you want all the values you have to use "Incremental Retrieval of Multi-valued Properties".

A utility class that takes care of all the details would be really useful.

References:
http://www.watersprings.org/pub/id/draft-kashi-incremental-00.txt
http://dunnry.com/blog/RangeRetrievalUsingSystemDirectoryServicesProtocols.aspx
http://msdn.microsoft.com/en-us/library/aa367017(VS.85).aspx
http://www.nntp.perl.org/group/perl.ldap/2005/02/msg1357.html

**Comment by spring-issuemaster** [comment]
This issue relates to #279
