### ISSUE TITLE
LDAP-192: Add authentication methods that provide authentication exception

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#230]
[Larry Yates](https://jira.spring.io/secure/ViewProfile.jspa?name=lyates) (Migrated from [LDAP-192](https://jira.spring.io/browse/LDAP-192?redirect=false)) said:

I realize that the AuthenticationException is logged, but I need to return this information to the caller so that they can seek remedy.

For example, if error is:
52e then user will know to re-enter password
530 then user will know to try later
532 then user will know password has expired
533 then user will know that account is disabled

etc....

If I have to use "plain old" JNDI for authentication purposes just to capture the AuthenticationException, then SPRING LDAP is useless to me.

Please make the ldaptemplate.authenticate throwable or somehow able to return the exception message instead of just FALSE.

**Comment by spring-issuemaster** [comment]
This issue duplicates #222
