### ISSUE TITLE
LDAP-266: Spring-data Automatic Repository Support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#241]
[Mattias Hellborg Arthursson](https://jira.spring.io/secure/ViewProfile.jspa?name=marthursson) (Migrated from [LDAP-266](https://jira.spring.io/browse/LDAP-266?redirect=false)) said:

It should be pretty simple to enable automatic Repository support in the spring-data fashion using ODM functionality.

**Comment by spring-issuemaster** [comment]
This issue depends on #307
This issue depends on #311
