### ISSUE TITLE
LDAP-228: Update entry with modify attributes in ODM manager

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#273]
[Erzhukov Victor](https://jira.spring.io/secure/ViewProfile.jspa?name=vthief) (Migrated from [LDAP-228](https://jira.spring.io/browse/LDAP-228?redirect=false)) said:

Update method in ODM manager involve ldapTemplate.rebind(...). Sometimes need use update method, witch involve ldapTemplate.modifyAttributes(...)

**Comment by spring-issuemaster** [comment]
This issue relates to #280
