### ISSUE TITLE
LDAP-236: Generate maven source artifacts for every artifact

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#281]
[Gert Dewit](https://jira.spring.io/secure/ViewProfile.jspa?name=gertux) (Migrated from [LDAP-236](https://jira.spring.io/browse/LDAP-236?redirect=false)) said:

There are no maven source artifacts, except for the top assembly.
Most IDE's (IntelliJ and Eclipse) support automatic downloading of sources for maven artifacts when they exist.

The current construction requires the user to manually attach the sources.

I've attached a path against r734 that implements this improvement.

**Comment by spring-issuemaster** [comment]
This issue duplicates #276
