### ISSUE TITLE
LDAP-244: Rebind commit fails under complex circumstances

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#287]
[Jose Noheda](https://jira.spring.io/secure/ViewProfile.jspa?name=xmaniac) (Migrated from [LDAP-244](https://jira.spring.io/browse/LDAP-244?redirect=false)) said:

a) Create an entity using ODM (in my case @Before in a JUNIT test)
a) Create a nested entity using the ODM (in a test method)
b) Delete the leaf one (same test method)
c) Read the leaf one and handle the NameNotFoundException gracefully (same test method)
d) Delete the parent one (in my case the @After method)

At that point Spring LDAP fails with an exception. The entity has correctly being renamed but the commit fails because it tries to unbind the incorrect entity. Instead of unbinding the renamed DN it appends the child Rdn as well and fails because the DN does not exist. Maybe the context is not fully cleaned after the first operations?spr

**Comment by spring-issuemaster** [comment]
This issue relates to #202
