### ISSUE TITLE
LDAP-248: Support for Name attribute values in DirContextAdapter (was:LdapRdnComponent lowercases key)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#289]
[Michael Osipov](https://jira.spring.io/secure/ViewProfile.jspa?name=michael-o) (Migrated from [LDAP-248](https://jira.spring.io/browse/LDAP-248?redirect=false)) said:

The class LdapRdnComponent always lowercases the keys. This behavior is not mentioned in RFC2253. I want my RDNs remain as-is/unmodified. Please remove the lowercase operation. DirContext#getNameInNamespace leaves the DN as-is.

**Comment by spring-issuemaster** [comment]
This issue depends on #297
This issue depends on #312
This issue depends on #313
