### ISSUE TITLE
LDAP-258: Modernize Spring LDAP API

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#297]
[Mattias Hellborg Arthursson](https://jira.spring.io/secure/ViewProfile.jspa?name=marthursson) (Migrated from [LDAP-258](https://jira.spring.io/browse/LDAP-258?redirect=false)) said:

The Spring LDAP core API should be modernized to use generics etc, similar to the overhaul of JdbcTemplate in Spring 3.0. Upgrade to Java 6.

`SimpleLdapTemplate` and the other classes in spring-ldap-core-tiger should be deprecated.

**Comment by spring-issuemaster** [comment]
This issue depends on #302
This issue depends on #304
This issue depends on #241
This issue depends on #305
