### ISSUE TITLE
LDAP-261: Enable configuration of default timeLimit, countLimit and searchScope in LdapTemplate

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#300]
[Mattias Hellborg Arthursson](https://jira.spring.io/secure/ViewProfile.jspa?name=marthursson) (Migrated from [LDAP-261](https://jira.spring.io/browse/LDAP-261?redirect=false)) said:

This would enable use of less verbose method signatures, e.g. if the same time limit is to be used for each and every search operation.

**Comment by spring-issuemaster** [comment]
This issue supersedes #203
