### ISSUE TITLE
LDAP-265: Move ODM functionality to LdapTemplate

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#304]
[Mattias Hellborg Arthursson](https://jira.spring.io/secure/ViewProfile.jspa?name=marthursson) (Migrated from [LDAP-265](https://jira.spring.io/browse/LDAP-265?redirect=false)) said:

Since everything is Java 5 now there's really no need for ODM to be a separate module. The `OdmManager` methods should be moved to `LdapTemplate`.

Configuration of managed classes should be made automatic, i.e. it should not be required to list the managed classes; the system can take care of that automatically.

spring-ldap-odm should be deprecated when this is in place.

**Comment by spring-issuemaster** [comment]
This issue depends on #306
This issue supersedes #237
