### ISSUE TITLE
LDAP-299: Deprecate spring-ldap-ldif-batch in favor of using modules in Spring Batch

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#334]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [LDAP-299](https://jira.spring.io/browse/LDAP-299?redirect=false)) said:

This is necessary to resolve project dependency cycles. ie) Spring Security -> Spring LDAP -> Spring Batch -> Spring Security

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/BATCH-2202
