### ISSUE TITLE
Incompatibility between Spring LDAP 2.0.4.RELEASE and Spring Data Rest 2.4.0.RELEASE (Gosling)

### ISSUE THREAD

**Issue by voidengineer** [spring-projects/spring-ldap#34]
When using Spring LDAP 2.0.4.RELEASE with Spring Data Rest 2.4.0.RELEASE application startup fails with an exception. Everything works with Spring Data Fowler.

I prepared a git repository demonstrating the error: 
https://github.com/voidengineer/spring-data-gosling-ldap

**Comment by rwinch** [comment]
Thanks for the report. This is a duplicate of #373
