### ISSUE TITLE
LDAP-310: Log LDAP queries generated by spring-ldap

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#345]
[Jose Martinez](https://jira.spring.io/secure/ViewProfile.jspa?name=jmartinez@knoa.com) (Migrated from [LDAP-310](https://jira.spring.io/browse/LDAP-310?redirect=false)) said:

I would be useful for the debugging purposes to have log the final query string sent to the server as well as the parameters. Something we can copy-paste into the LDAP server and see how it runs. Similar to the way JdbcTemplate shows the queries and parameters executing a query. 

I'm creating this Jira as per the following StackOverflow post: https://stackoverflow.com/questions/24061834/how-to-see-the-query-generated-by-spring-ldaptemplate.

**Comment by StevenByks** [comment]
I was trying to figure out how to turn on extra logging, and came across that exact SO post, which lead me here.  Debug logging would be so incredibly useful.

**Comment by kkrawczy** [comment]
+1, I also find it useful to see ldap queries.

**Comment by gael-ft** [comment]
+1

**Comment by nunoc** [comment]
+1

**Comment by hanusto** [comment]
+1

**Comment by chupetoide** [comment]
+1

**Comment by kutis96** [comment]
+1

**Comment by erdbeerschnitzel** [comment]
+2 :)

**Comment by rwinch** [comment]
Does someone want to create a PR for this?

**Comment by naorbar** [comment]
Rob,
I'll take a look...
Naor

**Comment by mastermind3043** [comment]
+1

**Comment by tofuatjava** [comment]
+1

**Comment by lafferty-common** [comment]
+1

**Comment by khafizovar** [comment]
+1

**Comment by KrashLeviathan** [comment]
+1 Has this really been an open issue for 8 years?

**Comment by ranma2913** [comment]
+1 again. Having trouble understanding the ldap query behavior when comparing what ApacheDirectoryStudio returns vs. Spring-Data-LDAP.
