### ISSUE TITLE
LDAP-312: more flexibility for attribute mapping

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-ldap#347]
[Brett Maxfield](https://jira.spring.io/secure/ViewProfile.jspa?name=maxfieb) (Migrated from [LDAP-312](https://jira.spring.io/browse/LDAP-312?redirect=false)) said:

There seems be some things missing in the Spring-LDAP ODM annotations. 
1. I'd like to mark an @Attribute as read-only, so it will populate the bean from LDAP for reference, but not persist it back to ldap. I'd suggest adding an attribute read-only to @Attribute, defaulting to false, for the usual case.
2. The default attributes of \* misses all the operational attributes, some of which are very useful, and transfers more data than is required, slowing down the ldap query with attributes which will never be used.

An example of this; it would be very useful, for literally read only, such as entryUUID, etag, etc., which you cannot use if you wish to persist only some fields back to ldap, as the bean fails to persist to ldap with an exception when you save the bean. But also would be useful for general fields which you want to structurally prevent the user from ever updating.

You can get around this by not annotating read-only fields, and then manually populating the read only fields with a separate call. Very messy and kills the query speed.

Also on a related topic, query() could have a default list of attributes, which you have already annotated in your classes, something like :

public static String[] getBeanAttributes(Class<?> beanClass) {
    ArrayList<String> attrsObj = new ArrayList<>();
    for (Field field : beanClass.getDeclaredFields()) {
        if (field.isAnnotationPresent(Attribute.class)) {
            Attribute attr = field.getAnnotation(Attribute.class);
            attrsObj.add(attr.name());
        }
    }
    String[] attrs = attrsObj.toArray(new String[attrsObj.size()]);
    return attrs;
}

Above just returns a simple String[] of your declared attributes, to pass to query.attributes() - now i realize that as a static member, query() is built before the bean class is known, but at least there could be a helper function like the above, or a method signature for query attributes() that took a bean Class signature as an argument.

**Comment by kwin** [comment]
The patch being attached to https://jira.spring.io/browse/LDAP-312 does not correctly request only those attributes being found in the metadata in the methods 

1. `<T> T findByDn(Name dn, Class<T> clazz)`
1. `<T> T findOne(LdapQuery query, Class<T> clazz)`
1. `<T> List<T> find(LdapQuery query, Class<T> clazz)`
1. `<T> List<T> findAll(Class<T> clazz)`
1. `<T> List<T> findAll(Name base, SearchControls searchControls, Class<T> clazz)`
1. `<T> List<T> findAll(Name base, Filter filter, SearchControls searchControls, Class<T> clazz)`

Only for method 3 it is currently possible to explicitly request some operational attributes by putting those into the `query` param.

**Comment by maxfieb** [comment]
this is working pretty well for me, using latest spring-data-ldap (for the LDAP Repository) and spring-ldap (for the LdapTekplate / odm components)
