### ISSUE TITLE
LDAP-316: support for apache commons-pool2

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#351]
[Cristi Vulpe](https://jira.spring.io/secure/ViewProfile.jspa?name=cristian.vulpe) (Migrated from [LDAP-316](https://jira.spring.io/browse/LDAP-316?redirect=false)) said:

I have tried to upgrade from commons-pool version 1.6 to commons-pool2 version 2.2 and I get this exception:

```
java.lang.NoClassDefFoundError: org/apache/commons/pool/KeyedPoolableObjectFactory
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
    at java.lang.Class.getDeclaredMethods(Class.java:1962)
    at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:570)
    at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:489)
    at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:473)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:241)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1059)
    at 
....
```

I have a bean that looks like this:

``` xml
  <bean id="ldapContextSource"
    class="org.springframework.ldap.pool.factory.PoolingContextSource">
    ...
  </bean>
```

When I looked at the source code for PoolingContextSource.java I found that it is using the naming convention from commons-pool 1.x:

```
import org.apache.commons.pool.impl.GenericKeyedObjectPool;
```

.
Is it possible to:
1. Upgrade to the latest version (will very likely break backwards compatibility)?
2. Provide an implementation that is sensitive to the classpath entries (i.e. detect which implementation to use)?

**Comment by salmanVD** [comment]
@spring-issuemaster This issue still exists with latest Ldap core 2.3.2 release. When this will be fixed?

**Comment by snytkine** [comment]
I too have this issue right now with spring boot 2.2.3
The whole reason for using spring-ldap was the idea of support for ldap pool, but unfortunately there is this bug.
Is anyone working on fixing this issue?

**Comment by nulliver** [comment]
> I too have this issue right now with spring boot 2.2.3
> The whole reason for using spring-ldap was the idea of support for ldap pool, but unfortunately there is this bug.
> Is anyone working on fixing this issue?

@snytkine @salmanVD commons-pool2 is working fine for me with Spring LDAP Core version 2.3.2. One thing you have to consider is that there are two classes, one is for commons-pool and the other is for commons-pool2. 

For commons-pool 1.x use the class:
`org.springframework.ldap.pool.factory.PoolingContextSource`

For commons-pool 2.x use class:
`org.springframework.ldap.pool2.factory.PooledContextSource`

Note that the first one is in the **pool** subpackage and the second on the **pool2** subpackage. Also, the name of the commons-pool2 class starts with **Pooled** while the commons-pool 1 starts with **Pooling**

The Spring LDAP documentation does not mention this difference in the Pooling Support section, I found out about this by looking at the code of spring-ldap-core.
