### ISSUE TITLE
LDAP-341: Incompatibility between Spring LDAP 2.0.4.RELEASE and Spring Data Rest 2.4.0.RELEASE (Gosling)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#373]
[Sören Chittka](https://jira.spring.io/secure/ViewProfile.jspa?name=s%C3%B6ren%20chittka) (Migrated from [LDAP-341](https://jira.spring.io/browse/LDAP-341?redirect=false)) said:

When using Spring LDAP 2.0.4.RELEASE with Spring Data Rest 2.4.0.RELEASE application startup fails with an exception. Everything works with Spring Data Fowler.

I prepared a git repository demonstrating the error: 
https://github.com/voidengineer/spring-data-gosling-ldap

**Comment by spring-issuemaster** [comment]
This issue duplicates https://jira.spring.io/browse/DATAREST-473
