### ISSUE TITLE
LDAP-343: DirContextAdapter incorrectly throws IllegalArgumentException when adding Name attributes

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-ldap#375]
[Krzysztof Pado](https://jira.spring.io/secure/ViewProfile.jspa?name=krzysztof.pado@schibsted.pl) (Migrated from [LDAP-343](https://jira.spring.io/browse/LDAP-343?redirect=false)) said:

`addAttributeValue` method of `DirContextAdapter` fails with "java.lang.IllegalArgumentException: This instance has non-string attribute values; cannot handle Name values" when value of Name type is passed as value parameter, if previously another Name value was added.

The following code fails at line 3:
{{1: DirContextOperations operations = new DirContextAdapter("CN=group,DC=root");
2: operations.addAttributeValue("member", LdapUtils.newLdapName("CN=test,DC=root"));
3: operations.addAttributeValue("member", LdapUtils.newLdapName("CN=test2,DC=root"));}}

However, when first attribute is set as string, not as Name it runs fine:
{{1: DirContextOperations operations = new DirContextAdapter("CN=group,DC=root");
2: operations.addAttributeValue("member", "CN=test,DC=root");
3: operations.addAttributeValue("member", LdapUtils.newLdapName("CN=test2,DC=root"));}}

*Technical analysis:*
In `NameAwareAttribute(String id, Object value)` constructor value is added to `values` field, but there is no check whether value is instance of a Name, and `initValuesAsNames` method is not called. This causes an error in next `public boolean add(Object attrVal)` invocation with attrVal of type Name.

**Comment by rwinch** [comment]
Thanks for the PR @eddumelendez! This is now merged into master which means it will be part of 2.1.

**Comment by eddumelendez** [comment]
@rwinch should this issue be closed?

**Comment by rwinch** [comment]
@eddumelendez Yes it should. Thanks! I didn't notice the commit comment did not include Fix in it.
