### ISSUE TITLE
Add tests against Spring Data Snapshots

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-ldap#381]
This will help us detect problems like #380 earlier

**Comment by wilkinsona** [comment]
+1

FWIW, If you have an IO Platform Compability build that tests against 2.1, it'll show this failure.

**Comment by rwinch** [comment]
Thanks @wilkinsona I did get the error in CI (see https://build.spring.io/browse/LDAP-SIO-JOB1-697/log), but not until Spring IO was updated. Hopefully this will make it so we get the error before Spring Data updates

**Comment by rwinch** [comment]
PS: I should add that I think the other problem is the trigger was only done on commit rather than nightly.

**Comment by wilkinsona** [comment]
Understood. The earlier we can catch this sort of thing the better. Perhaps Boot and the Platform should be more aggressive about adopting snapshots of dependencies that we're planning to update? I didn't update Boot to Hopper until its M1 had been released. With hindsight, that delay may not have been a good idea.

**Comment by rwinch** [comment]
@wilkinsona I would love to have the SNAPSHOT version of Platform to be updated as soon as possible! 

I already run against Spring IO SNAPSHOT nightly (at least for most of my projects).This would have the benefit of find potential problems w/ other modules too.

**Comment by jzheaux** [comment]
Closed in 74396cac1b727a3fb8d459e4f767355bb19073aa
