### ISSUE TITLE
 RFC 2849 Base64 newlines should start with " "

### ISSUE THREAD

**Issue by sebi-hgdata** [spring-projects/spring-ldap#413]
Printing to ldif format is done by calling the toString() method on LdapAttributes, it in turn, for base64 values, will call https://github.com/spring-projects/spring-ldap/blob/master/core/src/main/java/org/springframework/ldap/support/LdapEncoder.java#L247.
For long values the ldif format asks a ' ' (space) at the beginning of the lines. 

At line  https://github.com/spring-projects/spring-ldap/blob/master/core/src/main/java/org/springframework/ldap/support/LdapEncoder.java#L260 a space needs to be added after ```\n```

**Comment by rwinch** [comment]
Thanks for the report. More specifically this is what [RFC 2849](https://tools.ietf.org/html/rfc2849) has to say:

> Any non-empty line, including comment lines, in an LDIF file
> MAY be folded by inserting a line separator (SEP) and a SPACE.
> Folding MUST NOT occur before the first character of the line.
> In other words, folding a line into two lines, the first of
> which is empty, is not permitted. Any line that begins with a
> single space MUST be treated as a continuation of the previous
> (non-empty) line. When joining folded lines, exactly one space
> character at the beginning of each continued line must be
> discarded. Implementations SHOULD NOT fold lines in the middle
> of a multi-byte UTF-8 character.
