### ISSUE TITLE
What's New in 2.2

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-ldap#420]
Add What's New in 2.2 section to the reference

**Comment by andrei-ivanov** [comment]
Commons Pool 2 is already supported in 2.1, gh-405, included in 2.2, just fixes the documentation.

**Comment by rwinch** [comment]
Thanks for pointing this bug out! Any chance you would be interested in
sending a pull request?

**Comment by andrei-ivanov** [comment]
PR sent
