### ISSUE TITLE
Missing artifact org.springframework.ldap:spring-ldap:jar:1.3.2.RELEASE

### ISSUE THREAD

**Issue by weathery** [spring-projects/spring-ldap#457]
Description	Resource	Path	Location	Type
Could download or Maven get error:
org.springframework.ldap:spring-ldap:jar:1.3.2.RELEASE

All of the following sites are the same：
`http://repo1.maven.org/maven2/`
`http://mvnrepository.com/artifact/org.springframework.ldap/spring-ldap`
`http://maven.aliyun.com/nexus/`

**Comment by erdbeerschnitzel** [comment]
You can find it here:

https://mvnrepository.com/artifact/org.springframework.ldap/spring-ldap-core/
