### ISSUE TITLE
LDAP-8: Add support for TLS connections

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#46]
["Ulrik Sandberg":https://jira.spring.io/secure/ViewProfile.jspa?name=ulsa](Migrated from ["LDAP-8":https://jira.spring.io/browse/LDAP-8?redirect=false]) said:

TLS connections should be supported by Spring LDAP.

**Comment by spring-issuemaster** [comment]
This issue depends on #50
This issue depends on #162
