### ISSUE TITLE
LDAP-9: Add support to manually follow referrals

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#47]
["Ulrik Sandberg":https://jira.spring.io/secure/ViewProfile.jspa?name=ulsa](Migrated from ["LDAP-9":https://jira.spring.io/browse/LDAP-9?redirect=false]) said:

Support should be added to automatically follow referrals in LdapTemplate, catching ReferralExceptions and 'manually' following the referral.

**Comment by spring-issuemaster** [comment]
This issue depends on #174
