### ISSUE TITLE
Client side Load Balancing

### ISSUE THREAD

**Issue by mattwmj** [spring-projects/spring-ldap#498]
Does spring-ldap has client side load balancing features?
If does, how to config?
If not, will it be implement in the future?
And if I want to add client side load balancing myself, where shall I start?

I see that unboundid ldap sdk has client side load balancing features. Is it possible to config spring-ldap to use unboundid to connect ldap server?

Thank you!

**Comment by ParkerM** [comment]
Basic fail-over functionality is included and can be used by supplying multiple URL's to the `spring.ldap.urls` property (see [here](https://docs.spring.io/spring-ldap/docs/current/reference/#contextsource-configuration)), but I don't believe something like round-robin or geo-based load balancing is built in. Such functionality would typically be offloaded onto the directory server(s) themselves. It _could_ probably be implemented manually in the client, or better yet through a separate proxy service. The amount of control you have over the directory servers would determine which solution would work best in your case.

**Comment by ParkerM** [comment]
@rwinch could we close this please?
