### ISSUE TITLE
Puzzled about the boolean authenticate .

### ISSUE THREAD

**Issue by Koooooo-7** [spring-projects/spring-ldap#537]
- Springboot version: 2.0.3.RELEASE
- Ldap version: 
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-ldap</artifactId>
            <version>2.1.6.RELEASE</version>
        </dependency>
```
---

According to the [reference document](https://docs.spring.io/spring-ldap/docs/current/reference/#user-authentication) from `https://docs.spring.io`。
> Spring LDAP includes an authenticate method in LdapTemplate that provide this functionality: **boolean** authenticate(LdapQuery query, String password);
>Using this method authentication becomes as simple as this:
>Authenticating a user using Spring LDAP.
```java
ldapTemplate.authenticate(query().where("uid").is("john.doe"), "secret");
```
the source code :
```java
    /**
     * {@inheritDoc}
     */
    @Override
    public void authenticate(LdapQuery query, String password) {
        authenticate(query,
                password,
                new NullAuthenticatedLdapEntryContextCallback());
    }
```

and I  tried to debug find the method
```java
authenticate(query,password,newNullAuthenticatedLdapEntryContextCallback());
```
Authenticate success return the `mapperCallback.collectedObject` is  **null**.

**Puzzled**  :
- the **boolean** authenticate method return is void .
- it  is a little bit weird when I use this authenticate method, the best result is nothing happen.

**Comment by jzheaux** [comment]
@Koooooo-7 thanks for bringing this up. In the documentation section you refer to, there are two authenticate methods. The first is a proposed custom method and the second is the Spring-provided one. It's not meant for them to have the same signature.

I agree that this could be made clearer in the docs. My plan is to update the docs to show the Spring-provided method first and then talk about customizing.
