### ISSUE TITLE
NameAwareAttributes#remove should be case insensitive

### ISSUE THREAD

**Issue by 0x0000-dot-ru** [spring-projects/spring-ldap#548]
According to inherithed javadoc from javax.naming.directory.Attributes this method should be case insenitive. This bug breaks remove attribute logic in org.springframework.ldap.core.DirContextAdapter#update.

https://docs.oracle.com/javase/7/docs/api/javax/naming/directory/Attributes.html#remove(java.lang.String) says
"If the attribute set ignores the character case of its attribute ids, the case of attrID is ignored."

**Comment by rwinch** [comment]
Thanks for the report @0x0000-dot-ru are you interested in submitting a PR?
