### ISSUE TITLE
Is there any plan to rebuild some demo to springboot?

### ISSUE THREAD

**Issue by turtler000** [spring-projects/spring-ldap#558]
The XML Configurations are really kind of cumbersome,is there any plan to rebuild or create a demo using springboot to configure?

**Comment by rwinch** [comment]
Thanks for the report! Would you be interested in submitting a Pull Request?

**Comment by turtler000** [comment]
I am very honored to be invited .But I never user gradle and I'm busy for work.So it may takes a while time for me.
