### ISSUE TITLE
password change with LDAP operation (RFC 3062)

### ISSUE THREAD

**Issue by RedDragonet** [spring-projects/spring-ldap#563]
[spring-security](https://github.com/spring-projects/spring-security/issues/3392) already support this feature.

Is spring-ldap support this feature?

**Comment by rwinch** [comment]
No changes were necessary with Spring LDAP. See https://github.com/spring-projects/spring-security/commit/7269aacbdd42183afeedc84e2233580b917da4c0 for how Spring Security supports RFC 3062 with Spring LDAP

**Comment by RedDragonet** [comment]
thanks
