### ISSUE TITLE
ldap只查询用户不查询联系人，计算机等怎么处理？官网没有找到相关说明

### ISSUE THREAD

**Issue by lixm17** [spring-projects/spring-ldap#566]
用户配置如下：
public class LdapUserAttributeMapper  implements AttributesMapper<LdapUser>{
    @Override
    public LdapUser mapFromAttributes(Attributes attrs) throws NamingException {
        LdapUser user  = new LdapUser();
        if(attrs.get("sAMAccountName") != null){
            user.setOaAccount( attrs.get("sAMAccountName").get().toString());
        }
       ...
}}
查询配置如下：
 LdapTemplate ldapTemplate=new LdapTemplate(LdapConfiguration.contextSource(url,base,userDn,pwd));

            EqualsFilter filter = new EqualsFilter("objectclass", "person");

            List<LdapUser> search = ldapTemplate.search("", filter.encode(), new LdapUserAttributeMapper());

**Comment by lixm17** [comment]
@rmorgan @nebhale @trevormarshall @bclozel

**Comment by jzheaux** [comment]
Please don't @ random people on the Spring team.

I'm not able to understand your request. Can you try rewording it in English? A minimal GitHub sample would also help.
