### ISSUE TITLE
LDAP-52: Rewrite VirtualListViewRequestControl using AggregateDirContextProcessor

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#57]
["Ulrik Sandberg":https://jira.spring.io/secure/ViewProfile.jspa?name=ulsa](Migrated from ["LDAP-52":https://jira.spring.io/browse/LDAP-52?redirect=false]) said:

The VLV control requires a SortControl. We have manually implemented the handling of the two in our VLVRequestControl, but the implementation could be improved by using the AggregateDirContextProcessor that already handles this in a generic way.

**Comment by spring-issuemaster** [comment]
This issue is related to #102
