### ISSUE TITLE
AbstractContextSource cannot be instantiated on JDK16+

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-ldap#570]
Hi,

I'm currently working on JDK 16 support for Spring Boot (see https://github.com/spring-projects/spring-boot/issues/24402) and noticed that `AbstractContextSource` cannot be instantiated as of JDK16+ anymore.

I guess this is related to the new strong encapsulation being enabled by default (see https://openjdk.java.net/jeps/396).

I can currently workaround this by passing `--add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED` but users would have the same problem again.

Cheers,
Christoph

**Comment by dreis2211** [comment]
The only actual usage inside the library itself seems to be the following:
```
env.put(Context.INITIAL_CONTEXT_FACTORY, contextFactory.getName());
```
One idea would be to deprecate `setContextFactory(Class)` & `getContextFactory()` in favor of `setContextFactoryName(String)` & `getContextFactoryName()` and a new field `contextFactoryName` that is instantianted with `com.sun.jndi.ldap.LdapCtxFactory` instead of referencing the class.

What do you think?

**Comment by dreis2211** [comment]
Alternatively, #568 should also work.

**Comment by jzheaux** [comment]
Thanks, @dreis2211! I believe you are correct that #568 will take care of this.
