### ISSUE TITLE
Update typica dependency to 1.7.2

### ISSUE THREAD

**Issue by dol** [spring-projects/spring-ldap#575]
### Intro
typica is used as a transient dependency in https://github.com/spring-projects/spring-ldap/blob/142496c4c447210f8f04726fe49419e424cf7378/test-support/build.gradle#L5 .

### Request
**It would be nice to update the typica library to a newer, most recent version.**

### Reason why
The current version 1.3 has a broken pom.xml ( https://repo1.maven.org/maven2/com/google/code/typica/typica/1.3/typica-1.3.pom ) which causes some issues with our maven caching proxy. The maven proxy is not able to parse a broken pom.xml. In version 1.7.2 (latest) to pom.xml looks valid and our maven caching proxy has no problem with it.

![image](https://user-images.githubusercontent.com/41777/110638166-80323a00-81ae-11eb-90db-1f419376c250.png)

**Comment by erdbeerschnitzel** [comment]
+1
