### ISSUE TITLE
Add support to return a Java 8 `Stream` from `LdapTemplate`

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-ldap#586]
It would be great if `LdapTemplate` could bridge `NamingEnumeration` into a Java 8 `Stream` exposing the following methods:

```java
Stream<T> find(LdapQuery query, Class<T> clazz);

Stream<T> find(LdapQuery query, ContextMapper<T> mapper);
```

This would be useful in the context of Spring Data to natively expose the LDAP result as stream without collecting results into a `Collection`. Since `NamingEnumeration` is closeable, the `Stream` needs to be closed after consumption but that is a regular requirement when used in other modules such as `JdbcTemplate.queryForStream(…)` or JPA stream queries.

#501 seems a related ticket.

**Comment by jzheaux** [comment]
Thanks for the suggestion, @mp911de. 

How did you decide on those two methods? Several `LdapTemplate` methods return a `List` and could possibly benefit from a `Stream` equivalent. Or, IOW, I'm wondering if any other methods should be considered.

**Comment by jzheaux** [comment]
After some further analysis, it seems `search(LdapQuery, ContextMapper<T>)` is a better fit. Also, `search(LdapQuery, AttributeMapper<T>)` could benefit from a `Stream` option.

What I'd recommend are the following three new methods:

```java
Stream<T> findStream(LdapQuery query, Class<T> clazz);

Stream<T> searchStream(LdapQuery query, AttributeMapper<T> mapper);

Stream<T> searchStream(LdapQuery query, ContextMapper<T> mapper);
```

**Comment by mp911de** [comment]
`findStream`/`searchStream` are going into the right direction. Maybe just `stream` for a less clunky name. 

A method returning `Stream` and accepting `ContextMapper` seems weird at first sight (one could always call `stream.map(mapper::mapFromContext)` but given that `mapFromContext` can throw an exception, the design proposal makes sense.
