### ISSUE TITLE
Broken links on https://spring.io/projects/spring-ldap#learn

### ISSUE THREAD

**Issue by fy-gualtiero-testa** [spring-projects/spring-ldap#661]
The learn page (https://spring.io/projects/spring-ldap#learn) contains broken links to the reference documentation.

For example, current version documentation link is  https://docs.spring.io/spring-ldap/docs/current/reference/html/

while the html page is located in https://docs.spring.io/spring-ldap/docs/current/reference

**Comment by jzheaux** [comment]
Thanks, good catch, @fy-gualtiero-testa. All fixed now.
