### ISSUE TITLE
spring-ldap-ldif-batch:jar:2.4.0 has not been deployed on maven central

### ISSUE THREAD

**Issue by bellidori** [spring-projects/spring-ldap#664]
Could not find artifact org.springframework.ldap:spring-ldap-ldif-batch:jar:2.4.0

https://mvnrepository.com/artifact/org.springframework.ldap/spring-ldap-ldif-batch
![spring-ldap-ldif-batch-maven-central](https://user-images.githubusercontent.com/2261065/173884141-05b0c43a-55eb-4416-8516-55cb0beb58d9.png)
h

**Comment by jzheaux** [comment]
This project has been removed. Please see https://github.com/spring-projects/spring-ldap/issues/662 and https://github.com/spring-projects/spring-ldap/issues/334 for details.

[Equivalent files](https://github.com/spring-projects/spring-batch/tree/main/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/ldif) are available in Spring Batch.
