### ISSUE TITLE
Spring LDAP Native Support

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-ldap#676]
- [x] Review native smoke tests for Spring LDAP, add tickets for missing tests
  - https://github.com/spring-projects/spring-aot-smoke-tests/issues/88
- [x] Add tickets for missing Spring LDAP native support, based on smoke test results
  - https://github.com/spring-projects/spring-ldap/issues/699

**Comment by marcusdacoregio** [comment]
We have [this sample](https://github.com/spring-projects/spring-aot-smoke-tests/tree/main/security-ldap) in spring-aot-smoke-tests. What are other sample scenarios that you think should go there?

**Comment by jzheaux** [comment]
That's great, @marcusdacoregio, thanks. That sample seems to be testing Spring Security's integration with Spring LDAP.

I think one area of interest specific to Spring LDAP would be [ODM](https://docs.spring.io/spring-ldap/docs/current/reference/#odm) [(example)](https://github.com/spring-projects/spring-ldap/blob/main/core/src/main/java/org/springframework/ldap/core/LdapTemplate.java#L1880) since it uses reflection.

**Comment by marcusdacoregio** [comment]
https://github.com/spring-projects/spring-aot-smoke-tests/issues/88
