### ISSUE TITLE
Current documentation points to 2.3.8.RELEASE

### ISSUE THREAD

**Issue by bendem** [spring-projects/spring-ldap#773]
https://docs.spring.io/spring-ldap/docs/current/reference/ mentions the version it was built from, which is 2.3.8. Meanwhile, the actually current documentation is available at https://docs.spring.io/spring-ldap/docs/3.1.x/reference/#preface.

Not sure where to report this so here it is :)

**Comment by FerretDave** [comment]
6 months on and the link to the documentation is still wrong?
Also worth noting that the 3.1 docs only actually go so far as 'whats new in 2.2' and reference xml config, which is outdated now? So is that page actually the right one anyway?
Using the latest spring LDAP appears to be using the new version, but there's no documentation covering how to 'bind' with this version.
@marthursson @ulsa @rwinch can you advise?

**Comment by jzheaux** [comment]
The up-to-date documentation link is https://docs.spring.io/spring-ldap/reference/ - I will take a look at see what can be done about the other link so that it redirects.

**Comment by jzheaux** [comment]
Thanks for the report, @bendem. The URL now redirects to the updated https://docs.spring.io/spring-ldap/reference.

Also, the most up-to-date doc references are listed at https://projects.spring.io/spring-ldap#learn
