### ISSUE TITLE
LDAP-39: Provide utility method for simple authentication

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#81]
["Ulrik Sandberg":https://jira.spring.io/secure/ViewProfile.jspa?name=ulsa](Migrated from ["LDAP-39":https://jira.spring.io/browse/LDAP-39?redirect=false]) said:

A popular request is that Spring LDAP should provide a simple authentication mechanism for those that don't need the full power of Acegi Security. One approach that seems to work is this (taken from the forum http://forum.springframework.org/showthread.php?t=29063):

public boolean checkPassword(String login, String password) {
    log.debug("LdapServiceDao::checkPassword()");

```
// Construction du DN
DistinguishedName dn = new DistinguishedName("ou=People,dc=univ,dc=fr");
dn.append(new DistinguishedName(getUserDn(login)));

// Connexion manuelle
LdapContextSource ctxSource = new LdapContextSource();
ctxSource.setUrl(url);
ctxSource.setUserName(dn.encode());
ctxSource.setPassword(password);
ctxSource.setPooled(false);
try {
    ctxSource.afterPropertiesSet();
    ctxSource.getReadWriteContext();
    return true;
}
catch(Exception e) {
    return false;
}
}
```

**Comment by spring-issuemaster** [comment]
This issue depends on #143
