### ISSUE TITLE
Log message in `AbstractContextSource` is misleading

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-ldap#833]
The following log message produced by the following line is misleading based on the documentation:

https://github.com/spring-projects/spring-ldap/blob/16f2626a4d388486cc7f49b6e5cc8aaeaccb3ec5/core/src/main/java/org/springframework/ldap/core/support/AbstractContextSource.java#L419

it says: "Property 'userDn' not set - anonymous context will be used for read-write operations". Right after that, the `anonymousReadOnly` property is set to `true`.

However, in [the documentation](https://docs.spring.io/spring-ldap/docs/current/reference/#code-contextsource-code-configuration), the `anonymousReadOnly` property is described as (emphasis by me):

> Defines whether **read-only** operations are performed by using an anonymous (unauthenticated) context. Note that setting this parameter to true together with the compensating transaction support is not supported and is rejected.

This is causing confusion about whether the log message is erroneous or the anonymous context is being used for read-write operations.

**Comment by dbnex14** [comment]
@marcusdacoregio any chance the documentation can be updated to reflect the great explanation you provided in the related issue you closed?  Thank you
