### ISSUE TITLE
DefaultObjectDirectoryMapper prevents updating objectClasses in spring-data-ldap

### ISSUE THREAD

**Issue by oscarbrookssynacor** [spring-projects/spring-ldap#835]
Hi, I opened in issue in spring-data-ldap, however after some more research it seems that this is a more fitting place for it. 

I am trying to accomplish the following: 
```
@Data
@Entry(base = "", objectClasses = { "SomeObjectClass" })
public class SomeEntry {
    private @Attribute(name = "objectClass") List<String> objectClasses;
    private @Attribute(name = "attributeRequiredByOtherObjectClass") String someAttribute;
}


SomeEntry entry =  someEntryRepository.findBy...(...);
entry.getObjectClasses().add("OtherObjectClass");
entry.setSomeAttribute("Value")
someEntryRepository.save(entry);
```
Currently I am getting an error 
```
javax.naming.directory.SchemaViolationException: [LDAP: error code 65 - attribute 'attributeRequiredByOtherObjectClass' not allowed]
```
If I perform the same operation on an entry that already has the objectClass "OtherObjectClass" the operation succeeds. 

After some looking it appears that this is the line responsible for this issue:
https://github.com/spring-projects/spring-ldap/blob/16f2626a4d388486cc7f49b6e5cc8aaeaccb3ec5/core/src/main/java/org/springframework/ldap/odm/core/impl/DefaultObjectDirectoryMapper.java#L164

I am not sure why this logic is there but it seems to me that it is a bug, since it is preventing a valid use-case of adding a new objectClass and its required fields. 

An undesirable workaround looks something like this: 

```
entry.getObjectClasses().add("OtherObjectClass");
DirContextOperations context = ldapTemplate.lookupContext(entry.getId());
context.setAttributeValues("objectClass", domainEntry.getObjectClass().toArray());
context.setAttributeValue("attributeRequiredByOtherObjectClass", domainEntry.getSomeAttribute());
ldapTemplate.update(domainEntry);
```

**Comment by jzheaux** [comment]
Thanks for reaching out, @oscarbrookssynacor. The ODM support is designed around the attributes that pertain to the object classes listed in the `@Entry` annotation for a given Java class. From the perspective of the Java class, the object classes are part of the class definition and not part of each entry.

As such, if you need to administer the object metadata, you should use `LdapTemplate` directly:

```java
DirContextOperations context = ldapTemplate.lookupContext(name);
String[] objectclass = context.getAttributeValues("objectclass");
objectclass = Arrays.copyOf(objectclass, objectclass.length + 1);
objectclass[objectclass.length - 1] = "OtherObjectClass";
context.setAttributeValues("objectclass", objectclass);
ldapTemplate.modifyAttributes(context);
```

And if you need to administer other attributes, use ODM:

```java
entry.setSomeAttribute("Value");
ldapTemplate.save(entry);
```

I'm going to close this as answered. Please feel free to reach out and provide more information if it looks like I've misunderstood.

**Comment by oscarbrookssynacor** [comment]
Thank you, the separation makes sense, and what you described is the route I ended up taking. 
Cheers.
