### ISSUE TITLE
Does the software support JKD21?

### ISSUE THREAD

**Issue by jin-pian** [spring-projects/spring-ldap#920]

**Comment by jzheaux** [comment]
Hi, @jin-pian, thanks for reaching out. Yes, the `3.2.x` line works with JDK 21. I've added a [CI step](https://github.com/spring-projects/spring-ldap/actions/runs/11134491198) now to keep track of this.

**Comment by jin-pian** [comment]
Thanks, But our actual test now found that version 3.2.10 cannot be compiled under jdk21

**Comment by jzheaux** [comment]
Can you provide more details? The CI continues to report that compilation succeeds with JDK 21. I've also run it on my local machine just now and it passed.

We might be talking about slightly different things, though. Can you please post the error that you are getting?
